sudo: false
language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - RUSTUP_HOME=/usr/local/rustup CARGO_HOME=/usr/local/cargo PATH=/usr/local/cargo/bin:$PATH

before_install:
  - wget https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
  - chmod +x rustup-init
  - ./rustup-init -y --no-modify-path --default-toolchain nightly
  - chmod -R a+w $RUSTUP_HOME $CARGO_HOME
  - rustup toolchain install nightly-2019-06-20 && nightly-2019-96-20
install: pip install tox-travis tox pyo3-pack==0.6.1 setuptools-rust==0.10.6
script: tox
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
  skip_existing: true
